Use mono prefix for nuget.exe and exit if it fails. Fixes #778.

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,3 +1,5 @@
 #!/bin/bash
-./tools/nuget.exe restore nunit.sln
+mono ./tools/nuget.exe restore nunit.linux.sln
+if [ "$?" -ne 0 ]; then echo "NuGet restore failed."; exit 1; fi
+
 xbuild "$@"
